name = "json-html"
type = "javascript"

main = "functions/index.js"

compatibility_date = "2025-02-28"

[site]
bucket = "./dist"

[[kv_namespaces]]
binding = "jsonToolKV"
id = "c01e099ade23487898085ce3bee3769e"
preview_id = "preview-id"

compatibility_flags = ["nodejs_compat"]

